algo = input('Escreva algo:')
print('Qual é o tipo primitivo desse valor?', type(algo))
print('É Alfabético?', algo.isalpha())
print('É Numero?',algo.isnumeric())
print('É alfanumérico?',algo.isalnum())
print('Esta em maiusculo?',algo.isupper())
print('Esta em minusculo?',algo.islower())
print('Esta capitalizado?',algo.istitle())
print('Só tem espaço?',algo.isspace())
